### ISSUE TITLE
'yt-dlp' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by devAshutoshkarn** [zackees/ytclip-server#2]
When i run this application on my window 11 this happen:-
![Here is the error of image](https://user-images.githubusercontent.com/82864637/223806775-d5ae1888-12cc-41c1-ad3b-f46a46de2e10.png)
 
please solve this .

**Comment by zackees** [comment]
Please provide repro steps. I have not seen this issue at all.

**Comment by devAshutoshkarn** [comment]
when i clone this project ytclip-server on my window 11 machine and click on run_dev.sh all things working fine. But when i click on download button it shows **"Backend process failed. Please try again."**  and in **run_dev.sh** it shows 
**'yt-dlp' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by zackees** [comment]
Thanks. I'll try and repro

**Comment by zackees** [comment]
Can you do do a full pip uninstall of:

```
pip uninstall ytclip
pip uninstall yt-dlp
pip uninstall ytclip-server
```

Then run `run_dev.sh` again and paste the output here? I think that there might be an install failure that is happening during pip install and this is causing yt-dlp to not be found. yt-dlp is included transitively by `ytclip` and I don't see this issue happening in any of the machines I've used it on. But I don't use Windows 11 yet.

**Comment by zackees** [comment]
Or just try and do `pip install yt-dlp` and paste what happens.

**Comment by devAshutoshkarn** [comment]
After reinstalling the project. it working like charm in window 11
thanks for this amazing tool.
